# Port for web server
# If you use port 80, you'll need to run server.coffee using sudo.
# This isn't super secure right now so be warned.

listenPort: 8080

# Default hipchat configs
# To enable, you'll need to set the hipchat.token configuration to your API key

hipchat:
  room: Starbound
  user: Server
  color: yellow
  notify: false
